#!/usr/bin/env python3

"""

Софт обязан быть локализованным (i18n)

В readme должны быть указаны рекомендуемые
приложения, а также список поддерживаемого
программного обеспечения
(alacritty, foot, kitty, mako, mc, ranger,
vi, vim, neovim, nano, micro, sway, wofi, waybar)

Софт, необходимый для корректной работы sway
(протестировано на Arch Linux):
    sway, swaybg, swaylock-effects-git (AUR),
    swayidle, waybar, wofi, mako,
    xorg-xwayland (по желанию), pipewire,
    pipewire-alsa, pipewire-pulse, wireplumber,
    pavucontrol, networkmanager,
    network-manager-applet

Под sway без xorg-xwayland работают:
    firefox, telegram-desktop,
    libreoffice-still, alacritty,
    foot, gimp, inkscape

Не работают:
    network-manager-applet,
    onlyoffice-bin, discord,
    visual-studio-code-bin,
    продукты jetbrains

Предупредить о том, что папки с текущей
конфигурацией и файл .bash_profile будут
радикально обновлены

Добавить функционал установки переменных
окружения в .bash_profile, а также
программ в автозапуск (sway exec)

1.  Написать приветственный текст

2.  Вывести предупреждение о том,
    что система обязана быть кристалльно
    чистой (установлен только дистрибутив
    и нужные для работы приложения), а
    также уточнить, что данный скрипт
    предназначен для дистрибутивов,
    работающих на systemd или openrc

3.  Уточнить тип "процесса 1" (для 3.1 и 3.2
    выводить отладочную информацию):
3.1 При systemd в .bash_profile добавить
    только exec sway
3.2 При openrc в .bash_profile добавить
    команды на подключение pipewire

3.  Предложить к выбору темы
    (названия берутся из названии папок
    в папке themes)

4.  Предложить к выбору приложения,
    на которые будет установлена
    выбранная ранее тема
4.1 alacritty/foot/kitty
4.2 mako (найти аналоги)
4.3 mc/ranger
4.4 vim/vi/nvim/nano/micro
4.5 sway/waybar/wofi

5.  Для каждого приложения уточнить
    кнфигурацию пунктов, которая может
    варьироваться (например, размер
    меню, которое выводится wofi)

6.  Скопировать полученную конфигурацию
    в папку текущего пользователя

7.  Доложить о том, что система нуждается
    в перезагрузке (для запуска программ
    автостарта)

"""


if __name__ == "__main__":
    pass
